ccflags-y += -Wframe-larger-than=4192

obj-$(CONFIG_TOUCHSCREEN_FT8720M) += focaltech_test.o
obj-$(CONFIG_TOUCHSCREEN_FT8720M) += focaltech_test_ini.o
obj-$(CONFIG_TOUCHSCREEN_FT8720M) += supported_ic/
